version: "2"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /vagrant/nginx-proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - gitlab_default
      - gitlabce_default

networks:
  gitlab_default:
    external: true
  gitlabce_default:
    external: true
