version: "2"

services:
  gitlab:
    build:
      context: ./gitlab-ce
    ports:
      - "80"
      - "443"
      - "10022:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - /vagrant/nginx-proxy/certs:/etc/gitlab/ssl
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.192.168.33.10.xip.io'
        registry_external_url 'https://registry.192.168.33.10.xip.io'
        mattermost_external_url 'https://mattermost.192.168.33.10.xip.io'
        user['uid'] = 998
        user['gid'] = 998
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'smtp.gmail.com'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'my.email@gmail.com'
        gitlab_rails['smtp_password'] = 'my-gmail-password'
        gitlab_rails['smtp_domain'] = 'smtp.gmail.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/common.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/common.key'
        registry_nginx['ssl_certificate'] = '/etc/gitlab/ssl/common.crt'
        registry_nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/common.key'
        mattermost_nginx['ssl_certificate'] = '/etc/gitlab/ssl/common.crt'
        mattermost_nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/common.key'
        mattermost['service_enable_insecure_outgoing_connections'] = true
      VIRTUAL_HOST: gitlab.192.168.33.10.xip.io,registry.192.168.33.10.xip.io,mattermost.192.168.33.10.xip.io
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      CERT_NAME: common

  redmine:
    build:
      context: ./redmine
    ports:
      - "3000"
    volumes:
      - redmine-files:/usr/src/redmine/files
      - /vagrant/gitlab-ce/redmine/plugins:/usr/src/redmine/plugins
    volumes_from:
      - gitlab
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: example
      VIRTUAL_HOST: redmine.192.168.33.10.xip.io
      CERT_NAME: common
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - redmine-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: example

volumes:
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local
  redmine-files:
    driver: local
  redmine-data:
    driver: local
